---
# Source: openwhisk/templates/couchdb-pod.yaml
#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#


apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuvolaris-redpanda
  labels:
    name: nuvolaris-redpanda
    app: nuvolaris-openwhisk
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nuvolaris-redpanda
  strategy:
    type: "Recreate"
  template:
    metadata:
      labels:
        name: nuvolaris-redpanda
        app: nuvolaris-openwhisk
    spec:
      restartPolicy: Always
      containers:
      - name: redpanda
        image: "docker.vectorized.io/vectorized/redpanda:latest"
        imagePullPolicy: "IfNotPresent"
        #command: ["sleep", "inf"]
        command: ["/opt/redpanda/bin/redpanda", "--redpanda-cfg", "/etc/redpanda/redpanda.yaml", "--overprovisioned", "--smp=1", "--memory=1G", "--lock-memory=false", "--reserve-memory=0M"]
        ports:
        - name: redpanda
          containerPort: 9092
        - name: redpanda-admin
          containerPort: 9644
        env:
        - name: "ENVIRONMENT_NAME"
          value: "redpanda"
        - name: "BOOTSTRAP"
          value: "127.0.0.1:9092"
        - name: "REPLICATION_FACTOR"
          value: "1"
        - name: "CLUSTER_ID"
          value: "red-panda-1"

